<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net11.0;net11.0-browser</TargetFrameworks>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
    <PackageId>Sia.Graphics</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sia.RenderGraph\Sia.RenderGraph.csproj" />
    <ProjectReference Include="..\Sia.WebGPU\Sia.WebGPU.csproj" />
    <PackageReference Include="Sia.Prelude" Version="2.1.2" />
    <PackageReference Include="Sia.Math" Version="0.0.3" />
    <PackageReference Include="Sia.CodeGenerators" Version="2.1.2" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net11.0-browser'">
    <SupportedOSPlatformVersion>0.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="UI/Render/Shaders/ui_node.wgsl" />
  </ItemGroup>
</Project>
