<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net11.0;net11.0-browser</TargetFrameworks>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageId>Sia.Graphics</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sia.RenderGraph\Sia.RenderGraph.csproj" />
    <ProjectReference Include="..\Sia.WebGPU\Sia.WebGPU.csproj" />
    <PackageReference Include="Sia.Prelude" Version="2.1.0" />
  </ItemGroup>
</Project>
