using System.Reflection;
using Sia.Spirv.Naga.IR;
using Sia.Spirv.Naga.Back;
string directory = Path.GetFullPath("Sia.Graphics/Sia.Spirv.Naga.Tests/bin/Release/net10.0");
System.Runtime.Loader.AssemblyLoadContext.Default.Resolving += (_, name) => File.Exists(Path.Combine(directory, name.Name + ".dll")) ? Assembly.LoadFrom(Path.Combine(directory, name.Name + ".dll")) : null;
var type = Assembly.LoadFrom(Path.Combine(directory, "Sia.Spirv.Naga.Tests.dll")).GetType("Sia.Spirv.Naga.Tests.QueryHelperTests", true)!;
var module = (Sia.Spirv.Naga.IR.Module)type.GetMethod("RawDescriptorModule", BindingFlags.Static | BindingFlags.NonPublic)!.Invoke(null, null)!;
Directory.CreateDirectory(".work/naga-csharp/raw-query-state");
File.WriteAllBytes(".work/naga-csharp/raw-query-state/input.spv", SpirvWriter.Write(module));
File.WriteAllText(".work/naga-csharp/raw-query-state/direct.wgsl", WgslWriter.Write(module));
