use std::{env, fs, path::PathBuf};

fn main() {
    let crate_directory = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("Cargo did not provide CARGO_MANIFEST_DIR"),
    );
    let include_directory = crate_directory.join("target").join("include");
    let header = include_directory.join("sia_spirv_naga.h");
    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        style: cbindgen::Style::Both,
        include_guard: Some("SIA_SPIRV_NAGA_H".into()),
        cpp_compat: true,
        usize_is_size_t: true,
        line_endings: cbindgen::LineEndingStyle::LF,
        documentation: false,
        autogen_warning: Some("/* Generated by cbindgen. Do not edit manually. */".into()),
        ..Default::default()
    };

    fs::create_dir_all(&include_directory).expect("Creating the generated header directory failed");
    cbindgen::Builder::new()
        .with_crate(&crate_directory)
        .with_config(config)
        .rename_item("SiaSpirvAbi", "sia_spirv_abi")
        .rename_item("SiaSpirvContext", "sia_spirv_context")
        .exclude_item("NAGA_VERSION")
        .generate()
        .expect("Generating the Sia SPIR-V C header failed")
        .write_to_file(header);

    println!("cargo:rerun-if-changed=src/lib.rs");
}
