<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageDescription>Managed SPIR-V and WGSL shader translation.</PackageDescription>
    <PackageLicenseFile>Naga.LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>
  <ItemGroup>
    <None Update="Naga.LICENSE.txt" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
