<Project Sdk="Microsoft.NET.Sdk.WebAssembly">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0-browser</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <WasmEnableSIMD>true</WasmEnableSIMD>
    <WasmBuildNative>true</WasmBuildNative>
    <WasmAllowUndefinedSymbols>true</WasmAllowUndefinedSymbols>
    <EmccFlags>--use-port=emdawnwebgpu</EmccFlags>
    <EmccExtraLDFlags>-sUSE_GLFW=3 -sALLOW_MEMORY_GROWTH</EmccExtraLDFlags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="obj_desktop\**" />
    <EmbeddedResource Remove="obj_desktop\**" />
    <None Remove="obj_desktop\**" />
    <Content Remove="obj_desktop\**" />
  </ItemGroup>

  <ItemGroup>
    <StaticWebAssetFingerprintPattern Include="JS" Pattern="*.js" Expression="#[.{fingerprint}]!" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sia.Graphics\Sia.Graphics.csproj" />
    <ProjectReference Include="..\Sia.WebGPU\Sia.WebGPU.csproj" />
    <PackageReference Include="Sia.GLFW" Version="0.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Fonts\*.ttf">
      <LogicalName>Sia.WebGPU.Example.Fonts.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="AddBrowserNativeModules"
          BeforeTargets="_GenerateManagedToNative"
          DependsOnTargets="PrepareForWasmBuildNative">
    <ItemGroup>
      <_WasmPInvokeModules Include="__Internal_emscripten" />
      <_WasmPInvokeModules Include="__Internal_glfw" />
    </ItemGroup>
  </Target>

</Project>
