<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="obj_browser\**" />
    <EmbeddedResource Remove="obj_browser\**" />
    <None Remove="obj_browser\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sia.Graphics\Sia.Graphics.csproj" />
    <ProjectReference Include="..\Sia.WebGPU\Sia.WebGPU.csproj" />
    <ProjectReference Include="..\Sia.WebGPU.Native\Sia.WebGPU.Native.csproj" />
    <PackageReference Include="Sia.GLFW" Version="0.0.1" />
    <PackageReference Include="Sia.GLFW.Native" Version="0.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Fonts\*.ttf">
      <LogicalName>Sia.WebGPU.Example.Fonts.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
