namespace Sia.WebGPU.Generators;

internal sealed class WgpuCodeRenderer
{
    private readonly WgpuGenerationOptions _options;
    private readonly WgpuTypeTranslator _types;

    public WgpuCodeRenderer(WgpuHeader header, WgpuGenerationOptions options)
    {
        _options = options;
        _types = new WgpuTypeTranslator(header);
    }

    public string RenderEnum(WgpuEnum @enum) =>
        RenderCompilationUnit(
            @enum.IsFlags ? "using System;" : string.Empty,
            $$"""
            {{(@enum.IsFlags ? "[Flags]\n" : string.Empty)}}public enum {{@enum.Name}} : {{@enum.UnderlyingType}}
            {
            {{RenderEnumValues(@enum.Values)}}
            }
            """);

    public string RenderHandle(WgpuHandle handle) =>
        RenderCompilationUnit(
            "using System.Runtime.InteropServices;",
            $$"""
            [StructLayout(LayoutKind.Sequential)]
            public unsafe struct {{handle.Name}}
            {
            }
            """);

    public string RenderStruct(WgpuStruct @struct) =>
        RenderCompilationUnit(
            "using System.Runtime.InteropServices;",
            $$"""
            [StructLayout(LayoutKind.Sequential)]
            public unsafe struct {{@struct.Name}}
            {
            {{RenderFields(@struct.Fields)}}
            }
            """);

    public string RenderCallback(WgpuCallback callback) =>
        RenderCompilationUnit(
            "using System.Runtime.InteropServices;",
            $$"""
            [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
            public unsafe delegate {{_types.Translate(callback.ReturnType)}} {{callback.Name}}({{RenderParameters(callback.Parameters)}});
            """);

    public string RenderFunction(WgpuFunction func, string className) =>
        RenderCompilationUnit(
            "using System.Runtime.InteropServices;",
            $$"""
            public static partial class {{className}}
            {
                #if BROWSER
                [DllImport("__Internal_emscripten", EntryPoint = "{{func.Name}}", CallingConvention = CallingConvention.Cdecl)]
                #else
                [DllImport("wgpu_native", EntryPoint = "{{func.Name}}", CallingConvention = CallingConvention.Cdecl)]
                #endif
                public static extern unsafe {{_types.Translate(func.ReturnType)}} {{func.Name}}({{RenderParameters(func.Parameters)}});
            }
            """);

    private string RenderCompilationUnit(string usings, string body) =>
        string.Join(
            WgpuNames.NewLine,
            new[]
            {
                "// <auto-generated />",
                "#nullable enable",
                usings,
                $"namespace {_options.Namespace};",
                body,
            }.Where(static section => !string.IsNullOrWhiteSpace(section)));

    private static string RenderEnumValues(IEnumerable<WgpuEnumValue> values) =>
        string.Join(WgpuNames.NewLine, values.Select(static value => $"    {value.Name} = {value.Value},"));

    private string RenderFields(IEnumerable<WgpuField> fields) =>
        string.Join(WgpuNames.NewLine, fields.Select(field => $"    public {_types.Translate(field.Type)} {field.Name};"));

    private string RenderParameters(IEnumerable<WgpuParameter> parameters) =>
        string.Join(", ", parameters.Select(parameter => $"{_types.Translate(parameter.Type)} {parameter.Name}"));
}
