using Microsoft.CodeAnalysis.CSharp;

namespace Sia.WebGPU.Generators;

internal sealed class WgpuCodeRenderer
{
    private const string _enumZeroInitializerPrefix = "_wgpu_ENUM_ZERO_INIT(";
    private const int _initializerFieldIndentation = 8;
    private const int _indentationSize = 4;
    private const string _structZeroInitializer = "_wgpu_STRUCT_ZERO_INIT";

    private readonly WgpuGenerationOptions _options;
    private readonly WgpuTypeTranslator _types;
    private readonly WgpuConstant[] _constants;
    private readonly Dictionary<string, WgpuConstant> _constantsByNativeName;
    private readonly Dictionary<string, WgpuStructInitializer> _initializersByStruct;
    private readonly Dictionary<string, string> _initializerStructsByMacro;
    private readonly string[] _enumNames;

    public WgpuCodeRenderer(WgpuHeader header, WgpuGenerationOptions options)
    {
        _options = options;
        _types = new WgpuTypeTranslator(header);
        _constants = header.Constants;
        _constantsByNativeName = header.Constants.ToDictionary(
            static constant => constant.NativeName,
            StringComparer.Ordinal);
        _initializersByStruct = header.Initializers.ToDictionary(
            static initializer => initializer.StructName,
            StringComparer.Ordinal);
        _initializerStructsByMacro = header.Initializers.ToDictionary(
            static initializer => initializer.MacroName,
            static initializer => initializer.StructName,
            StringComparer.Ordinal);
        _enumNames = header.Enums
            .Select(static value => value.Name)
            .OrderByDescending(static name => name.Length)
            .ToArray();
    }

    public string RenderEnum(WgpuEnum @enum) =>
        RenderCompilationUnit(
            @enum.IsFlags ? "using System;" : string.Empty,
            $$"""
            {{(@enum.IsFlags ? "[Flags]\n" : string.Empty)}}public enum {{@enum.Name}} : {{@enum.UnderlyingType}}
            {
            {{RenderEnumValues(@enum.Values)}}
            }
            """);

    public string RenderHandle(WgpuHandle handle) =>
        RenderCompilationUnit(
            "using System.Runtime.InteropServices;",
            $$"""
            [StructLayout(LayoutKind.Sequential)]
            public unsafe struct {{handle.Name}}
            {
            }
            """);

    public string RenderStruct(WgpuStruct @struct)
    {
        _initializersByStruct.TryGetValue(@struct.Name, out var initializer);
        var defaultMember = initializer is null
            ? string.Empty
            : WgpuNames.NewLine + WgpuNames.NewLine + RenderDefaultInitializer(initializer);

        return RenderCompilationUnit(
            "using System.Runtime.InteropServices;",
            $$"""
            [StructLayout(LayoutKind.Sequential)]
            public unsafe struct {{@struct.Name}}
            {
            {{RenderFields(@struct.Fields)}}{{defaultMember}}
            }
            """);
    }

    public string RenderCallback(WgpuCallback callback) =>
        RenderCompilationUnit(
            "using System.Runtime.InteropServices;",
            $$"""
            [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
            {{RenderCallbackDeclaration(callback)}}
            """);

    public string RenderFunction(WgpuFunction func, string className) =>
        RenderCompilationUnit(
            "using System.Runtime.InteropServices;",
            $$"""
            public static partial class {{className}}
            {
                #if BROWSER
                [DllImport(
                    {{QuoteString(_options.BrowserLibraryName)}},
                    EntryPoint = {{QuoteString(func.Name)}},
                    ExactSpelling = true,
                    CallingConvention = CallingConvention.Cdecl)]
                #else
                [DllImport(
                    {{QuoteString(_options.LibraryName)}},
                    EntryPoint = {{QuoteString(func.Name)}},
                    ExactSpelling = true,
                    CallingConvention = CallingConvention.Cdecl)]
                #endif
                {{RenderFunctionDeclaration(func)}}
            }
            """);

    public string RenderConstants() =>
        RenderCompilationUnit(
            string.Empty,
            $$"""
            public static class WgpuConstants
            {
            {{string.Join(WgpuNames.NewLine, _constants.Select(RenderConstant))}}
            }
            """);

    private string RenderCompilationUnit(string usings, string body) =>
        string.Join(
            WgpuNames.NewLine + WgpuNames.NewLine,
            new[]
            {
                $"// <auto-generated />{WgpuNames.NewLine}#nullable enable",
                usings,
                $"namespace {_options.Namespace};",
                body,
            }.Where(static section => !string.IsNullOrWhiteSpace(section))) + WgpuNames.NewLine;

    private static string RenderEnumValues(IEnumerable<WgpuEnumValue> values) =>
        string.Join(WgpuNames.NewLine, values.Select(static value => $"    {value.Name} = {value.Value},"));

    private string RenderFields(IEnumerable<WgpuField> fields) =>
        string.Join(WgpuNames.NewLine, fields.Select(RenderField));

    private string RenderField(WgpuField field) =>
        $"    public {_types.Translate(field.Type)} {field.Name};";

    private string RenderCallbackDeclaration(WgpuCallback callback) =>
        $"public unsafe delegate {_types.Translate(callback.ReturnType)} " +
        $"{callback.Name}({RenderParameters(callback.Parameters)});";

    private string RenderFunctionDeclaration(WgpuFunction function) =>
        $"public static extern unsafe {_types.Translate(function.ReturnType)} " +
        $"{function.Name}({RenderParameters(function.Parameters)});";

    private string RenderParameters(IEnumerable<WgpuParameter> parameters) =>
        string.Join(
            ", ",
            parameters.Select(parameter =>
                $"{_types.Translate(parameter.Type)} {EscapeIdentifier(parameter.Name)}"));

    private static string RenderConstant(WgpuConstant constant)
    {
        var modifier = constant.IsCompileTimeConstant ? "const" : "static readonly";
        return $"    public {modifier} {constant.Type} {constant.Name} = {constant.Value};";
    }

    private string RenderDefaultInitializer(WgpuStructInitializer initializer) =>
        $$"""
            public static {{initializer.StructName}} Default => new()
            {
        {{RenderInitializerFields(initializer.Fields, _initializerFieldIndentation)}}
            };
        """;

    private string RenderInitializerFields(IEnumerable<WgpuInitializerField> fields, int indentation) =>
        string.Join(
            WgpuNames.NewLine,
            fields.Select(field => RenderInitializerField(field, indentation)));

    private string RenderInitializerField(WgpuInitializerField field, int indentation) =>
        $"{new string(' ', indentation)}" +
        $"{WgpuNameTransforms.ToPascalCase(field.Name)} = " +
        $"{RenderInitializerValue(field.Value, indentation)},";

    private string RenderInitializerValue(WgpuInitializerValue value, int indentation) =>
        value switch {
            WgpuScalarInitializerValue scalar => TranslateInitializerExpression(scalar.Expression),
            WgpuNestedInitializerValue nested => RenderNestedInitializer(nested, indentation),
            _ => throw new InvalidOperationException(
                $"Unsupported initializer value type '{value.GetType().FullName}'."),
        };

    private string RenderNestedInitializer(WgpuNestedInitializerValue initializer, int indentation)
    {
        var indent = new string(' ', indentation);
        return $$"""
        new {{initializer.StructName}}
        {{indent}}{
        {{RenderInitializerFields(initializer.Fields, indentation + _indentationSize)}}
        {{indent}}}
        """;
    }

    private string TranslateInitializerExpression(string expression)
    {
        if (_constantsByNativeName.TryGetValue(expression, out var constant)) {
            return $"WgpuConstants.{constant.Name}";
        }

        if (_initializerStructsByMacro.TryGetValue(expression, out var structName)) {
            return $"{structName}.Default";
        }

        if (expression.StartsWith(_enumZeroInitializerPrefix, StringComparison.Ordinal) &&
            expression.EndsWith(")", StringComparison.Ordinal)) {
            var enumName = expression.Substring(
                _enumZeroInitializerPrefix.Length,
                expression.Length - _enumZeroInitializerPrefix.Length - 1);
            return $"({enumName})0";
        }

        if (expression == _structZeroInitializer) {
            return "default";
        }

        foreach (var enumName in _enumNames) {
            var prefix = enumName + "_";
            if (expression.StartsWith(prefix, StringComparison.Ordinal)) {
                return $"{enumName}.{WgpuNameTransforms.NormalizeEnumValueName(expression, prefix)}";
            }
        }

        return expression switch {
            "NULL" => "null",
            "0" or "0." => "0",
            "0.f" => "0f",
            "32.f" => "32f",
            "0xFFFFFFFF" => "uint.MaxValue",
            _ when expression.All(char.IsDigit) => expression,
            _ => throw new InvalidOperationException($"Unsupported WebGPU initializer expression '{expression}'."),
        };
    }

    private static string EscapeIdentifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None
            ? "@" + name
            : name;

    private static string QuoteString(string value) =>
        SymbolDisplay.FormatLiteral(value, quote: true);
}
